POS/Controllers/POSManagementController.cs
using POS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;

namespace POS.Controllers
{
    public class POSManagementController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        #region CRUD
        /// <summary>
        /// Create View for purchase order
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Creates new purchase order for the given data
        /// </summary>
        /// <param name="posModel">Gets posModel</param>
        /// <returns>Returns read</returns>
        [HttpPost]
        public ActionResult Create(POSModel posModel)
        {
            POSDal.Create(posModel);
            return RedirectToAction("Read");
        }

        /// <summary>
        /// Edits the Purchase order details for the given id
        /// </summary>
        /// <param name="id">Purchase order id</param>
        /// <returns>Returns the read</returns>
        [HttpGet]
        public ActionResult Edit(int id)
        {
            POSModel.Id = id;
            POSModel = POSDal.GetPurchaseOrder(POSModel);
            return View("Create", POSModel);
        }

        /// <summary>
        /// Displays details for the given Purchase order id
        /// </summary>
        /// <param name="id">Purchase order id</param>
        /// <returns>Returns Purchase order details for the given id</returns>
        [HttpGet]
        public ActionResult Details(int id)
        {
            POSModel.Id = id;
            POSModel = POSDal.GetPurchaseOrder(POSModel);
            return View(POSModel);
        }

        /// <summary>
        /// Edit Purchase order details for the given id
        /// </summary>
        /// <param name="posModel">POSModel object</param>
        /// <returns>After successful updation redirects to Read method</returns>
        public ActionResult Edit(POSModel posModel)
        {
            POSDal.Update(posModel);
            return RedirectToAction("Read");
        }

        /// <summary>
        /// Read all Purchase order details
        /// </summary>
        /// <returns>Returns List of Purchase order</returns>
        public ActionResult Read()
        {
            List<POSModel> empList = new List<POSModel>();
            empList = POSDal.Read();
            return View(empList);
        }

        /// <summary>
        /// Deletes Purchase order details for the given id
        /// </summary>
        /// <param name="id">Purchase order id</param>
        /// <returns>Returns View with Purchase order details for delete</returns>
        [HttpGet]
        public ActionResult Delete(int id)
        {
            POSModel.Id = id;
            POSModel = POSDal.GetPurchaseOrder(POSModel);
            return View(POSModel);
        }

        /// <summary>
        /// Deletes the Purchase order for the given model
        /// </summary>
        /// <param name="posModel">Purchase order object</param>
        /// <returns>After deleting the records redirects to Read method </returns>
        [HttpPost]
        public ActionResult Delete(POSModel posModel)
        {
            POSDal.Delete(posModel);
            return RedirectToAction("Read");
        }
        #endregion

        #region Read Recent 5
        /// <summary>
        /// Get Recent changes through SqlCacheDependency
        /// </summary>
        /// <returns>Returns Partial view</returns>
        public ActionResult Recent()
        {
            List<POSModel> empList = new List<POSModel>();
            if (System.Web.HttpContext.Current.Cache["RecentPos"] != null)
            {
                empList = System.Web.HttpContext.Current.Cache["RecentPos"] as List<POSModel>;
            }
            else
            {
                string connStr = System.Configuration.ConfigurationManager.ConnectionStrings["POSConnection"].ConnectionString;
                System.Web.Caching.SqlCacheDependencyAdmin.EnableNotifications(connStr);
                System.Web.Caching.SqlCacheDependencyAdmin.EnableTableForNotifications(connStr, "PurchaseOrder");

                SqlCacheDependency sqlDependency = new SqlCacheDependency("CachingPOS", "PurchaseOrder");
                empList = POSDal.Recent();
                System.Web.HttpContext.Current.Cache.Insert("RecentPos", empList, sqlDependency);
            }

            return PartialView(empList);
        }

        #endregion

        #region Get Notification
        /// <summary>
        /// Get Notification
        /// </summary>
        /// <returns>Returns JSON Result of recent changes</returns>
        public JsonResult GetNotification()
        {
            var notificationRegisterTime = Session["LastUpdated"] != null ? Convert.ToDateTime(Session["LastUpdated"]) : DateTime.Now;
            NotificationComponent notificationComponent = new NotificationComponent();
            var list = notificationComponent.GetRecentChanges(notificationRegisterTime);

            return new JsonResult { Data = list, JsonRequestBehavior=JsonRequestBehavior.AllowGet };
        }
        #endregion
    }
}

POS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - POS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <span class="noti glyphicon glyphicon-bell"><span class="count">&nbsp;</span></span>
                <div class="noti-content">
                    <div class="noti-top-arrow">
                        <ul id="notiContent"></ul>
                    </div>
                </div>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"></button>
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="col-md-8">
            <div class="body-content">
                @RenderBody()
            </div>
        </div>

        <div id="recent-notifications" class="col-md-2">
            <h2>Cache-AJAX Refresh</h2>
            <div class="col-md-10">
                <div id="Recent">
                    @Html.Action("Recent", "POSManagement")
                </div>
            </div>

        </div>
        <div id="recent-notifications" class="col-md-2">
            <h2>SignalR-Instantaneous</h2>
            <div class="notification-area">
                <ul id="notification-Content"></ul>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="~/Scripts/jquery.signalR-2.2.1.min.js"></script>
    <script src="/signalr/hubs"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <script type="text/javascript">
        $(function () {
            setInterval(function () {
                $('#Recent').load('/POSManagement/Recent');
            }, 1000);
        });

        $(function () {
            $('span.noti').click(function (e) {
                e.stopPropagation();
                $('.noti-content').show();
                var count = 0;
                count = parseInt($('span.count').html()) || 0;

                if (count > 0) {
                    updateNotification();
                }
                $('span.count', this).html('&nbsp;');
            })
            // Hide notifications
            $('html').click(function () {
                $('.noti-content').hide();
            })

            // Updates notification
            function updateNotification() {
                $('#notiContent').empty();
                $('#notiContent').append($('<li>Loading...</li>'));

                $.ajax({
                    type: 'GET',
                    url: '/POSManagement/GetNotification',
                    success: function (data) {
                        $('#notiContent').empty();
                        if (data.length == 0) {
                            $('#notiContent').append($('<li>No data available</li>'));
                        }
                        $.each(data, function () {
                            $('#notiContent').append($('<li>' + this.OrderName + ' - ' + this.TimeStamp + '</li>'));
                        });
                    },
                    error: function (error) {
                        console.log(error);
                    }
                })
            }
            // update notification count
            function updateNotificationCount() {
                var count = 0;
                count = parseInt($('span.count').html()) || 0;
                count++;
                $('span.count').html(count);
            }

            var notificationHub = $.connection.notificationHub;
            $.connection.hub.start().done(function () {
                console.log('Notification hub started');
            });

            notificationHub.client.notify = function (message) {
                if (message && message.toLowerCase() == "newnotification") {
                    updateNotificationCount();
                    updateArea();
                }
            }

            function updateArea() {
                $('.notification-area').show();
                $('#notification-Content').empty();
                $.ajax({
                    type: 'GET',
                    url: '/POSManagement/GetNotification',
                    success: function (data) {
                        $('#notification-Content').empty();
                        if (data.length == 0) {
                            $('#notification-Content').append($('<li>No data available</li>'));
                        }
                        var i = 0;
                        $.each(data, function () {
                            i++;
                            if (i == 10)
                                return false;
                            $('#notification-Content').append($('<li>' + this.OrderName + ' - ' + this.TimeStamp + '</li>'));
                        });
                    },
                    error: function (error) {
                        console.log(error);
                    }
                })
            }
        })
    </script>

    <style type="text/css">
            a {
                color: black;
            }

            .body-content {
                margin-top: 55px;
                background-color: #d8cece;
                min-height: 590px;
                border: 1px solid black;
                z-index: 1;
                overflow-y: auto;
                border-radius: 4px;
                /*-webkit-box-shadow: 1px 1px 1px 1px rgba(0,0,0,0.75);
        -moz-box-shadow: 1px 1px 1px 1px rgba(0,0,0,0.75);
        box-shadow: 1px 1px 1px 1px rgba(0,0,0,0.75);*/
            }

            footer {
                text-align: center;
                background-color: #332e2e;
                color: white;
                height: 45px;
                border: 1px solid black;
            }

            .navbar {
                background-color: #332e2e;
                color: white;
                border: 1px solid black;
            }



            td {
                width: 200px;
            }

            td, th {
                border: 1px solid black !important;
            }

            #title {
                border-bottom: 1px solid gray;
                margin-bottom: 30px;
            }

            #recent-notifications {
                margin-top: 55px;
                background-color: #d8cece;
                min-height: 590px;
                border: 1px solid black;
                z-index: 1000;
                overflow-y: auto;
                border-radius: 4px;
            }

            .noti-content {
                position: fixed;
                right: 100px;
                background: #e5e5e5;
                border-radius: 4px;
                top: 47px;
                width: 250px;
                display: none;
                border: 1px solid #9E988B;
            }

            ul#notiContent {
                max-height: 200px;
                overflow: auto;
                padding: 0px;
                margin: 0px;
                padding-left: 20px;
            }

                ul#notiContent li {
                    margin: 5px;
                    padding: 6px;
                    background: #fff;
                    color: black;
                }

            .noti-top-arrow {
                border-color: transparent;
                border-bottom-color: #F5DEB3;
                border-style: dashed dashed solid;
                border-width: 0 8.5px 8.5px;
                position: absolute;
                right: 32px;
                top: -8px;
            }

            span.noti {
                color: #FF2323;
                margin: 15px;
                position: fixed;
                right: 100px;
                font-size: 18px;
                cursor: pointer;
            }

            span.count {
                position: relative;
                top: -3px;
            }
    </style>

</body>
</html>